version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
